### PR TITLE
bugfix/moved toolbar from -dev to core requirements:

### PR DESCRIPTION
**Pull request by gecBurton**
Previously `django-toolbar` was in the `INSTALLED_APPS` but only in `requirements-dev.txt` not `requirements.txt` so that it is always required even when not in dev/debug.

changes:
1. I have moved the `django_toolbar` requirement to `requirements.txt` 
2. I have hidden the toolbar url behind `DEBUG`
3. I have bumped the min test coverage to 70%

to test:
deploy to dev

### CODE REVIEW

**Review by 252afh — APPROVED** [review]

**Comment by duncanjbrown** [comment]
Is this right?

**Comment by duncanjbrown** [comment]
Don't we want to only include it in `INSTALLED_APPS` if we're actually in the dev env? It feels at best a bit inefficient and at worst mildly insecure to ship this in prod.

**Comment by gecBurton** [comment]
> Don't we want to only include it in `INSTALLED_APPS` if we're actually in the dev env? It feels at best a bit inefficient and at worst mildly insecure to ship this in prod.
> 
> eg
> 
> ```python
> if DEBUG:
>     INSTALLED_APPS.append('debug_toolbar`) # or whatever insertion method is required by ordering
> ```

fair point. i dont think its doing any harm just being installed but its certainly slowing us down in the middleware, ill remove it

**Review by duncanjbrown — APPROVED** [review]

**Comment by duncanjbrown** [comment]
Thanks!

**Pull request merged**
